import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { testFirebase } from "./firebase-test"; // import firebase test script

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  // Only run on server (so logs appear in terminal, not browser console)
  if (typeof window === "undefined") {
    testFirebase();
  }

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
